version: "3.8"

services:
  web:
    build:  build: ./porfolio  # This points to the correct directory where your Dockerfile is located
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=mysql://flaskapp:${MYSQL_PASSWORD}@mysql/flaskdb
    depends_on:
      - redis
      - mysql
    networks:
      - mynetwork

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: Tino2025!!!
      MYSQL_DATABASE: digitalart
      MYSQL_USER: Tchagaka
      MYSQL_PASSWORD: Tino2025!!!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge
